const appname = "Ecommerce Prodavač",
    login= "Prijava",
    welcome= "Zdravo, dobrodošli u",
    email= "Email",
    password = "Lozinka",
    forgotPassword = "Zaboravili ste lozinku?",
    anyProblem= "U slučaju problema, kontaktirajte administraciju",
    credit = "@Ecommerce",
    emailHint = "npr. vendor@gmail.com",
    passwordHint=  "******",
    confirmPass = "Potvrdite lozinku",
    loginTo = "Prijavi te se na vaš nalog",
    logout = "Odjavi se",
    dashboard = "Komandna tabla",
    products = "Proizvodi",
    settings = "Podešavanja",
    rating = "Ocjena",
    totalSales = "Ukupno prodato",
    unpaid = "Neplaćeno",
    popular = "Omiljeni proizvodi",
    featured = "Istaknuto",
    edit = "Uredi",
    name = "Korisničko ime",
    remove = "Ukloni",
    orders = "Narudžbe";

//shop settings
const nameHint = "pr. Ime firme",
    shopSettings = "Podešavanja prodavnice",
    messages = "Poruke",
    shopDescHint = "Unesite opis vaše prodavnice",
    shopWebsiteHint = "pr. firma@gmail.com",
    shopMobileHint = "111111111",
    shopAddressHint = "pr. kneza miroslava bb",
    description = "Opis",
    mobile = "Broj telefona",
    website = "Veb sajt",
    chats = "Ćaskanja",
    shopName = "Ime prodavnice",
    save  = "Sačuvaj",
    editProfile = "Uredi profil",
    changeImage = "Promijeni sliku",
    address  = "Adresa Prodavnice";



